spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/ping-pong?useSSL=true&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC
    username: dbuser
    password: awesomepassword
    driverClassName: com.mysql.cj.jdbc.Driver
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
  session:
    store-type: jdbc
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
logging:
  config: file:log4j2-dev.yml